apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-deployment
  template:
    metadata:
      labels:
        app: worker-deployment
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker
